# Baselines


```{python eval=FALSE,include=FALSE}
import datetime
from pyspark.sql import SparkSession
spark = SparkSession.builder.getOrCreate()
ms = spark.read.option("mergeSchema", "true").\
     parquet("s3://telemetry-parquet/main_summary/v4/")
ms.createOrReplaceTempView('ms')

import mozillametricstools.common.functions as mozfun
mozfun.register_udf(sqlContext
                    , lambda arr:  sum(arr) if arr else 0, "array_sum"
                    , pyspark.sql.types.IntegerType())


base='2017-01-01'
end = '2017-11-30'
delta = (datetime.datetime.strptime(end,"%Y-%m-%d")- datetime.datetime.strptime(base,"%Y-%m-%d")).days
DS = [ (datetime.datetime.strptime(base,"%Y-%m-%d").date()+datetime.timedelta(i)).strftime("%Y-%m-%d")  for i in range(delta+1)]
container=[]
for d in DS:
    print(d)
    v = spark.sql("""
    with a as (select
    client_id,
    sum(subsession_length/3600.0) as sessionHrs,
            sum(active_ticks*5.0)/sum(subsession_length*1.0) as inten,
            sum(coalesce(scalar_parent_browser_engagement_total_uri_count,0))/sum(subsession_length/3600.0) as uri,
            sum(coalesce(scalar_parent_browser_engagement_tab_open_event_count,0))/sum(subsession_length/3600.0) as tabs,
            sum(case
               when search_counts is not null then array_sum(search_counts.count) else 0
            end)/sum(subsession_length/3600.0) as search,
            (sum(coalesce(crash_submit_success_main,0))+
               sum(coalesce(crashes_detected_content, 0))- sum(coalesce(shutdown_kill,0))) as cr1,
            case when (sum(coalesce(crash_submit_success_main,0))+
               sum(coalesce(crashes_detected_content, 0))- sum(coalesce(shutdown_kill,0))) >0 then 1 else 0 end as crashed
    from ms
    where
    normalized_channel='release'
    and sample_id='42'
    and app_name='Firefox'
    and profile_creation_date={pcd}
    and submission_date>='{pcddate}' and submission_date<='{pcdend}'
    and subsession_length<=86400
    and subsession_length>=0
    and scalar_parent_browser_engagement_total_uri_count< 100000
    and scalar_parent_browser_engagement_tab_open_event_count < 100000
    group by 1)
    select '{pcddate}' as pcd,
    avg(sessionHrs) as sessionh,
    avg(inten) as minten,
    avg(uri) as muri,
    avg(tabs) as mtabs,
    avg(search) as msearch,
    sum(cr1*1.0)/sum(sessionHrs)*1000 as mcrate,
    avg(crashed) as mcrashed
    from a
    """.format(
        pcddate = datetime.datetime.strptime(d,"%Y-%m-%d").date().strftime("%Y%m%d"),
        pcdend  = (datetime.datetime.strptime(d,"%Y-%m-%d").date()+datetime.timedelta(6)).strftime("%Y%m%d"),
        pcd=   (datetime.datetime.strptime(d,"%Y-%m-%d").date()- datetime.datetime.strptime("1970-01-01","%Y-%m-%d").date()).days
    ))
    container.append(v.toPandas())


import pandas as pd
pd.concat(container).to_csv("~/baseline.csv")
import subprocess
subprocess.call(["aws", "s3", "cp", "/home/hadoop/baseline.csv", "s3://mozilla-metrics/user/sguha/tmp/baseline.csv"])

```

```{r eval=TRUE,cache=TRUE,include=FALSE,fig.caption='Session Hours Per Profile in their First Week',fig.width=8,fig.align='center'}
invisible({
    bl <- fread("~/tmp/baseline.csv")
    bl[,":="(V1=NULL,pcd=as.Date(as.character(pcd),'%Y%m%d'))]
})
doPlot <- function(var,title){
    xyplot(get(var) ~ pcd, xlab='Profile Creation Date', ylab='',
           type=c('g','l'),scale=list(x=list(tick.num=25,cex=0.6,rot=45)),data=bl,col='#cccccc',
           panel=function(x,y,...){
               panel.xyplot(x,y,...)
               y2=as.numeric(filter (y, rep(1,7)/7))
               panel.loess(x,y2,type='l',col='black',span=0.1)
           },main=title)
}
```

```{r eval=TRUE,cache=TRUE,fig.height=12,fig.width=12, fig.align='center'}
u1=doPlot('sessionh','Session length(hrs)/profile')
u2=doPlot('minten','Intensity of use/profile')
u3=doPlot('muri','URI/hour/profile')
u4=doPlot('mtabs','Tabs Opened/hour/profile')
u5=doPlot('msearch','Searches/hour/profile')
u6=doPlot('mcrate','Crash Rate')
u7=doPlot('mcrashed','Prop of Profiles Crashing')

print(u1,split=c(1,1,2,4),more=TRUE)
print(u2,split=c(2,1,2,4),more=TRUE)
print(u3,split=c(1,2,2,4),more=TRUE)
print(u4,split=c(2,2,2,4),more=TRUE)
print(u5,split=c(1,3,2,4),more=TRUE)
print(u6,split=c(2,3,2,4),more=TRUE)
print(u7,split=c(1,4,2,4),more=FALSE)
```
